version: '3'
services:
  
  fastapi:
    container_name: fastapi
    ports:
      - 8080:8080
    build: ./app
    volumes:
      - ./app:/code/app:rw
    restart: always
    links:
      - postgres:postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
    user: postgres
    # build: ./postgres
    # init_db:
      # build: ./postgres
      # command: python ./postgres/init_db.py
    restart: always