version: '3'
services:
  
  fastapi:
    container_name: fastapi
    ports:
      - 8080:8080
    build: ./app
    volumes:
      - ./app:/code/app:rw
    restart: always
    links:
      - postgres:postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    user: postgres
    restart: always